# gui/dockerfile.yml
FROM python:3.12-slim

WORKDIR /app

COPY client/namenode_client.py /app
COPY client/flask_app.py /app
COPY client/templates /app/templates
COPY client/static /app/static

RUN pip install --no-cache-dir requests flask

EXPOSE 5000

ENV DOWNLOAD_DIR="downloads"

CMD ["python", "flask_app.py"]
