# registry/dockerfile.yml
FROM python:3.12-slim

WORKDIR /app

COPY registry/registry.py /app/Registry/
COPY security /app/security
# Fijar versiones de bcrypt/passlib para evitar errores de backend
RUN pip install --no-cache-dir \
    fastapi uvicorn requests python-jose[cryptography] \
    passlib[bcrypt]==1.7.4 bcrypt==4.0.1

EXPOSE 9000

ENV HEARTBEAT_TIMEOUT=30
ENV CLEANUP_INTERVAL=10
ENV LEADER_HEARTBEAT_INTERVAL=5
ENV ELECTION_TIMEOUT=15

CMD ["uvicorn", "Registry.registry:app", "--host", "0.0.0.0", "--port", "9000"]

