# server/dockerfile.yml
FROM python:3.12-slim

WORKDIR /back

COPY core /back/core
COPY server /back/server
# COPY ./database /back/database

RUN pip install --no-cache-dir fastapi uvicorn requests python-multipart

EXPOSE 8000

CMD ["uvicorn", "server.api:app", "--host", "0.0.0.0", "--port", "8000"]