# namenode/dockerfile.yml
FROM python:3.12-slim

WORKDIR /app

COPY namenode /app/namenode
RUN pip install --no-cache-dir fastapi uvicorn requests

EXPOSE 8010

ENV HEARTBEAT_TIMEOUT=15 
ENV LEADER_HEARTBEAT_INTERVAL=5
ENV ELECTION_TIMEOUT=15
ENV NAMENODE_PORT=8010

CMD ["uvicorn", "namenode.namenode:app", "--host", "0.0.0.0", "--port", "8010"]

