# namenode/dockerfile.yml
FROM python:3.12-slim

WORKDIR /app

# Instalar sqlite3 y herramientas necesarias
RUN apt-get update && apt-get install -y \
    sqlite3 \
    && rm -rf /var/lib/apt/lists/*

COPY namenode /app/namenode
COPY security /app/security
# Fijar versiones de bcrypt/passlib para evitar errores de backend
RUN pip install --no-cache-dir \
    fastapi uvicorn requests python-multipart python-jose[cryptography] \
    passlib[bcrypt]==1.7.4 bcrypt==4.0.1

EXPOSE 8010

ENV HEARTBEAT_TIMEOUT=15 
ENV LEADER_HEARTBEAT_INTERVAL=5
ENV ELECTION_TIMEOUT=15
ENV NAMENODE_PORT=8010
ENV REGISTRY_URL=http://tbfs-registry-1:9000,http://tbfs-registry-2:9000,http://tbfs-registry-3:9000
ENV HEARTBEAT_INTERVAL=10

CMD ["uvicorn", "namenode.namenode:app", "--host", "0.0.0.0", "--port", "8010"]

